general_settings:
  execution_count: 9
  execution_mode: Бесконечный
  thread_count: 100
tasks_settings:
  1:
    retry_count2:
      hint: Количество попыток
      type: number
      value: 10
    task_name: Задача А
    username2:
      hint: Введите имя пользователя
      type: string
      value: user123
